import random

dummy_place = [
    # ── 12: 관광지 ──────────────────────────────────────────────────────────
    {
        "name": "경복궁",
        "address": "서울특별시 종로구 사직로 161",
        "category": "12",
        "description": "조선시대 대표 궁궐로 반려견과 함께 외부 산책로를 이용할 수 있습니다.",
        "latitude": 37.579617,
        "longitude": 126.977041,
        "content_type_id": "12",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "실외구역",
        "pet_size_limit": "소형견 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-3700-3900",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "북촌한옥마을",
        "address": "서울특별시 종로구 계동길 37",
        "category": "12",
        "description": "전통 한옥 골목길을 반려견과 함께 산책할 수 있는 서울 대표 관광지입니다.",
        "latitude": 37.582900,
        "longitude": 126.985300,
        "content_type_id": "12",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-731-0281",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "남산공원",
        "address": "서울특별시 용산구 남산공원길 105",
        "category": "12",
        "description": "서울 도심 속 자연을 즐길 수 있는 공원으로 반려견 산책이 가능합니다.",
        "latitude": 37.550872,
        "longitude": 126.988205,
        "content_type_id": "12",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-3783-5900",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "창덕궁",
        "address": "서울특별시 종로구 율곡로 99",
        "category": "12",
        "description": "유네스코 세계문화유산으로 지정된 궁궐로 외부 정원에서 반려견 동반이 가능합니다.",
        "latitude": 37.582800,
        "longitude": 126.991100,
        "content_type_id": "12",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "실외구역",
        "pet_size_limit": "소형견 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-762-8261",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "인왕산 둘레길",
        "address": "서울특별시 종로구 옥인동 산2",
        "category": "12",
        "description": "서울 도심에서 가볍게 즐기는 산책로로 반려견과 함께 트레킹이 가능합니다.",
        "latitude": 37.583000,
        "longitude": 126.965000,
        "content_type_id": "12",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    # ── 14: 문화시설 ─────────────────────────────────────────────────────────
    {
        "name": "국립한글박물관",
        "address": "서울특별시 용산구 서빙고로 139",
        "category": "14",
        "description": "한글의 역사와 문화를 전시하는 박물관으로 야외 정원에서 반려견 동반이 가능합니다.",
        "latitude": 37.524500,
        "longitude": 126.980200,
        "content_type_id": "14",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "실외구역",
        "pet_size_limit": "소형견 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용, 실내 입장 불가",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2124-6200",
        "conditions": "목줄 착용, 실내 입장 불가",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "서울시립미술관 서소문본관",
        "address": "서울특별시 중구 덕수궁길 61",
        "category": "14",
        "description": "서울 대표 공립미술관으로 야외 조각 공원에서 반려견 산책이 가능합니다.",
        "latitude": 37.565700,
        "longitude": 126.975300,
        "content_type_id": "14",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "실외구역",
        "pet_size_limit": "소형견 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용, 실내 입장 불가",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2124-8800",
        "conditions": "목줄 착용, 실내 입장 불가",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "DDP 동대문디자인플라자",
        "address": "서울특별시 중구 을지로 281",
        "category": "14",
        "description": "자하 하디드가 설계한 복합문화공간으로 야외 광장에서 반려견 동반이 가능합니다.",
        "latitude": 37.566900,
        "longitude": 127.009300,
        "content_type_id": "14",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "실외구역",
        "pet_size_limit": "소형견 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용, 실내 입장 불가",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2153-0000",
        "conditions": "목줄 착용, 실내 입장 불가",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "서울역사박물관",
        "address": "서울특별시 종로구 새문안로 55",
        "category": "14",
        "description": "서울의 역사와 문화를 전시하는 박물관으로 야외 공간에서 반려견 동반이 가능합니다.",
        "latitude": 37.571200,
        "longitude": 126.969800,
        "content_type_id": "14",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "실외구역",
        "pet_size_limit": "소형견 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용, 실내 입장 불가",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-724-0274",
        "conditions": "목줄 착용, 실내 입장 불가",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "국립현대미술관 서울관",
        "address": "서울특별시 종로구 삼청로 30",
        "category": "14",
        "description": "현대 미술 작품을 전시하는 미술관으로 야외 조각 공원에서 반려견 산책이 가능합니다.",
        "latitude": 37.578500,
        "longitude": 126.980600,
        "content_type_id": "14",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "실외구역",
        "pet_size_limit": "소형견 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용, 실내 입장 불가",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-3701-9500",
        "conditions": "목줄 착용, 실내 입장 불가",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    # ── 28: 레포츠 ──────────────────────────────────────────────────────────
    {
        "name": "서울숲",
        "address": "서울특별시 성동구 성수동1가 685",
        "category": "28",
        "description": "반려견과 함께 방문하기 좋은 서울의 공원입니다.",
        "latitude": 37.543066,
        "longitude": 127.041944,
        "content_type_id": "28",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-460-2905",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "올림픽공원",
        "address": "서울특별시 송파구 올림픽로 424",
        "category": "28",
        "description": "반려견과 함께 방문하기 좋은 서울의 공원입니다.",
        "latitude": 37.520000,
        "longitude": 127.120000,
        "content_type_id": "28",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-410-1114",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "월드컵공원",
        "address": "서울특별시 마포구 하늘공원로 95",
        "category": "28",
        "description": "반려견과 함께 방문하기 좋은 서울의 공원입니다.",
        "latitude": 37.570000,
        "longitude": 126.870000,
        "content_type_id": "28",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-300-5500",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "선유도공원",
        "address": "서울특별시 영등포구 선유로 343",
        "category": "28",
        "description": "반려견과 함께 방문하기 좋은 서울의 공원입니다.",
        "latitude": 37.530000,
        "longitude": 126.890000,
        "content_type_id": "28",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2631-9368",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "보라매공원",
        "address": "서울특별시 동작구 여의대방로20길 33",
        "category": "28",
        "description": "반려견과 함께 방문하기 좋은 서울의 공원입니다.",
        "latitude": 37.490000,
        "longitude": 126.920000,
        "content_type_id": "28",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2181-1182",
        "conditions": "목줄 착용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    # ── 32: 숙박 ────────────────────────────────────────────────────────────
    {
        "name": "그랜드 하얏트 서울",
        "address": "서울특별시 용산구 소월로 322",
        "category": "32",
        "description": "반려견 동반 투숙이 가능한 서울의 5성급 호텔입니다.",
        "latitude": 37.538700,
        "longitude": 126.991400,
        "content_type_id": "32",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "소형견(10kg 이하) 가능, 사전 신청 필수",
        "pet_restrictions": "사전 예약 시 반려동물 신청",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-797-1234",
        "conditions": "사전 예약 시 반려동물 신청",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "노보텔 앰배서더 서울 동대문",
        "address": "서울특별시 중구 을지로 249",
        "category": "32",
        "description": "도심에 위치한 반려견 동반 가능 호텔로 편리한 접근성을 자랑합니다.",
        "latitude": 37.566600,
        "longitude": 127.005500,
        "content_type_id": "32",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "소형견(8kg 이하) 가능, 사전 신청 필수",
        "pet_restrictions": "사전 예약 시 반려동물 신청",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2230-1234",
        "conditions": "사전 예약 시 반려동물 신청",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "L7 홍대 by LOTTE",
        "address": "서울특별시 마포구 양화로 141",
        "category": "32",
        "description": "홍대 중심부에 위치한 반려견 동반 가능 라이프스타일 호텔입니다.",
        "latitude": 37.556900,
        "longitude": 126.921800,
        "content_type_id": "32",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "소형견(7kg 이하) 가능, 사전 신청 필수",
        "pet_restrictions": "사전 예약 시 반려동물 신청, 반려동물 요금 별도",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-6906-7777",
        "conditions": "사전 예약 시 반려동물 신청, 반려동물 요금 별도",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "JW 메리어트 서울",
        "address": "서울특별시 서초구 반포대로 176",
        "category": "32",
        "description": "강남에 위치한 반려견 동반 가능 5성급 호텔입니다.",
        "latitude": 37.503600,
        "longitude": 127.005300,
        "content_type_id": "32",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "소형견(10kg 이하) 가능, 사전 신청 필수",
        "pet_restrictions": "사전 예약 시 반려동물 신청",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-6282-6262",
        "conditions": "사전 예약 시 반려동물 신청",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "파크 하얏트 서울",
        "address": "서울특별시 강남구 테헤란로 606",
        "category": "32",
        "description": "강남 삼성동에 위치한 반려견 동반 가능 럭셔리 호텔입니다.",
        "latitude": 37.508900,
        "longitude": 127.061500,
        "content_type_id": "32",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "소형견(10kg 이하) 가능, 사전 신청 필수",
        "pet_restrictions": "사전 예약 시 반려동물 신청",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2016-1234",
        "conditions": "사전 예약 시 반려동물 신청",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    # ── 38: 쇼핑 ────────────────────────────────────────────────────────────
    {
        "name": "더현대 서울",
        "address": "서울특별시 영등포구 여의대로 108",
        "category": "38",
        "description": "반려견 동반이 가능한 서울의 대형 복합쇼핑몰입니다. 전용 유모차 대여 서비스를 제공합니다.",
        "latitude": 37.526200,
        "longitude": 126.928600,
        "content_type_id": "38",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 이동가방 또는 유모차 탑승 필수",
        "pet_restrictions": "이동가방 또는 유모차 탑승 필수",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2163-2233",
        "conditions": "이동가방 또는 유모차 탑승 필수",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "롯데월드몰",
        "address": "서울특별시 송파구 올림픽로 300",
        "category": "38",
        "description": "반려견 동반이 가능한 대형 쇼핑몰로 반려동물 전용 편의시설이 마련되어 있습니다.",
        "latitude": 37.513100,
        "longitude": 127.102000,
        "content_type_id": "38",
        "is_indoor": True,
        "is_outdoor": False,
        "pet_zone_type": "실내구역",
        "pet_size_limit": "소형견(7kg 이하) 가능, 이동가방 탑승 필수",
        "pet_restrictions": "이동가방 탑승 필수",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-3213-4000",
        "conditions": "이동가방 탑승 필수",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "스타필드 코엑스몰",
        "address": "서울특별시 강남구 영동대로 513",
        "category": "38",
        "description": "강남 코엑스에 위치한 대형 쇼핑몰로 반려견 동반 입장이 가능합니다.",
        "latitude": 37.511200,
        "longitude": 127.059400,
        "content_type_id": "38",
        "is_indoor": True,
        "is_outdoor": False,
        "pet_zone_type": "실내구역",
        "pet_size_limit": "소형견 가능, 이동가방 탑승 필수",
        "pet_restrictions": "이동가방 탑승 필수",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-6002-5300",
        "conditions": "이동가방 탑승 필수",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "타임스퀘어",
        "address": "서울특별시 영등포구 영중로 15",
        "category": "38",
        "description": "영등포에 위치한 복합쇼핑몰로 반려견 동반 가능 구역이 마련되어 있습니다.",
        "latitude": 37.517700,
        "longitude": 126.903800,
        "content_type_id": "38",
        "is_indoor": True,
        "is_outdoor": False,
        "pet_zone_type": "실내구역",
        "pet_size_limit": "소형견 가능, 이동가방 탑승 필수",
        "pet_restrictions": "이동가방 탑승 필수",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2638-2000",
        "conditions": "이동가방 탑승 필수",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "가든파이브",
        "address": "서울특별시 송파구 충민로 10",
        "category": "38",
        "description": "송파구에 위치한 복합쇼핑몰로 반려견 동반 입장이 가능합니다.",
        "latitude": 37.490100,
        "longitude": 127.123900,
        "content_type_id": "38",
        "is_indoor": True,
        "is_outdoor": False,
        "pet_zone_type": "실내구역",
        "pet_size_limit": "소형견 가능, 이동가방 탑승 필수",
        "pet_restrictions": "이동가방 탑승 필수",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-2240-1000",
        "conditions": "이동가방 탑승 필수",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    # ── 39: 음식점 ──────────────────────────────────────────────────────────
    {
        "name": "멍멍 브런치 카페",
        "address": "서울특별시 마포구 연남동 227-20",
        "category": "39",
        "description": "연남동에 위치한 반려견 동반 브런치 카페로 야외 테라스를 운영합니다.",
        "latitude": 37.562500,
        "longitude": 126.923600,
        "content_type_id": "39",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용, 테라스 좌석 이용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-333-1234",
        "conditions": "목줄 착용, 테라스 좌석 이용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "퍼피 레스토랑 성수",
        "address": "서울특별시 성동구 성수이로 78",
        "category": "39",
        "description": "성수동에 위치한 반려견 동반 레스토랑으로 반려동물 전용 메뉴도 제공합니다.",
        "latitude": 37.544600,
        "longitude": 127.055700,
        "content_type_id": "39",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-465-5678",
        "conditions": "목줄 착용",
        "indoor": "Y",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "도그 카페 망원",
        "address": "서울특별시 마포구 망원동 425-5",
        "category": "39",
        "description": "망원동에 위치한 반려견 동반 카페로 넓은 실내 공간을 제공합니다.",
        "latitude": 37.555700,
        "longitude": 126.907400,
        "content_type_id": "39",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-322-9876",
        "conditions": "목줄 착용",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
    {
        "name": "펫 프렌들리 이태원",
        "address": "서울특별시 용산구 이태원로 177",
        "category": "39",
        "description": "이태원에 위치한 반려견 동반 가능 레스토랑으로 야외 테라스를 운영합니다.",
        "latitude": 37.534300,
        "longitude": 126.994500,
        "content_type_id": "39",
        "is_indoor": False,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능, 목줄 착용 필수",
        "pet_restrictions": "목줄 착용, 테라스 좌석 이용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-794-3456",
        "conditions": "목줄 착용, 테라스 좌석 이용",
        "indoor": "N",
        "outdoor": "Y",
        "similarity": 1.0,
    },
    {
        "name": "강아지와 한끼 홍대",
        "address": "서울특별시 마포구 와우산로 21길 19",
        "category": "39",
        "description": "홍대 인근 반려견 동반 한식 레스토랑으로 반려동물 간식을 제공합니다.",
        "latitude": 37.551900,
        "longitude": 126.924200,
        "content_type_id": "39",
        "is_indoor": True,
        "is_outdoor": True,
        "pet_zone_type": "전구역",
        "pet_size_limit": "전 견종 가능",
        "pet_restrictions": "목줄 착용",
        "firstimage": "",
        "firstimage2": "",
        "tel": "02-334-2222",
        "conditions": "목줄 착용",
        "indoor": "Y",
        "outdoor": "N",
        "similarity": 1.0,
    },
]


class Place:

    def __init__(self):
        pass

    async def find_place(self, top_k: int = 1) -> list[dict]:
        """
            더미 데이터에서 무작위로 top_k개 장소를 반환한다.
        """
        return random.sample(dummy_place, min(top_k, len(dummy_place)))
